/**
 * Chaves canônicas de permissões do módulo Pagadoria.
 *
 * Manter em sync com:
 * - roles.ts (presets)
 * - Plano: seção "Matriz de permissões"
 * - UI: RoleEditorDialog (agrupamento por categoria)
 */

export const PERMISSION = {
  // Organização e membros
  ORG_SETTINGS_READ: "org.settings.read",
  ORG_SETTINGS_EDIT: "org.settings.edit",
  ORG_MEMBERS_INVITE: "org.members.invite",
  ORG_MEMBERS_CHANGE_ROLE: "org.members.change_role",
  ORG_MEMBERS_REMOVE: "org.members.remove",
  ORG_DELETE: "org.delete",
  ORG_TRANSFER_OWNERSHIP: "org.transfer_ownership",

  // KYC e identidade
  KYC_SUBMIT: "kyc.submit",
  KYC_UPLOAD_DOCUMENT: "kyc.upload_document",
  KYC_VIEW_STATUS: "kyc.view_status",
  API_KEY_ROTATE: "api_key.rotate",
  API_KEY_VIEW_MASKED: "api_key.view_masked",
  ACCOUNT_CREATE: "account.create",
  ACCOUNT_ACTIVATE: "account.activate",
  ACCOUNT_ARCHIVE: "account.archive",
  ACCOUNT_PERMISSIONS_MANAGE: "account.permissions.manage",

  // Cobranças
  CHARGE_CREATE_FROM_DEAL: "charge.create.from_deal",
  CHARGE_CREATE_AVULSA: "charge.create.avulsa",
  CHARGE_VIEW_ALL: "charge.view.all",
  CHARGE_VIEW_OWN_DEALS_ONLY: "charge.view.own_deals_only",
  CHARGE_EDIT_DUE_DATE: "charge.edit_due_date",
  CHARGE_EDIT_DESCRIPTION: "charge.edit_description",
  CHARGE_CANCEL: "charge.cancel",
  CHARGE_REFUND: "charge.refund",
  CHARGE_RESEND_NOTIFICATION: "charge.resend_notification",
  CHARGE_MARK_RECEIVED_IN_CASH: "charge.mark_received_in_cash",

  // Clientes
  CUSTOMER_CREATE: "customer.create",
  CUSTOMER_EDIT: "customer.edit",
  CUSTOMER_DELETE: "customer.delete",
  CUSTOMER_VIEW_ALL: "customer.view.all",
  CUSTOMER_VIEW_OWN_DEALS: "customer.view.own_deals",

  // Split e taxas
  SPLIT_VIEW: "split.view",
  SPLIT_CONFIGURE: "split.configure",
  FEES_VIEW: "fees.view",
  FEES_CONFIGURE: "fees.configure",
  FEES_BRANDING_CONFIGURE: "fees.branding.configure",

  // Transferências e saldo
  FINANCE_BALANCE_VIEW: "finance.balance.view",
  FINANCE_STATEMENT_VIEW: "finance.statement.view",
  FINANCE_STATEMENT_EXPORT: "finance.statement.export",
  TRANSFER_INIT: "transfer.init",
  TRANSFER_CONFIRM_BELOW_CAP: "transfer.confirm_below_cap",
  TRANSFER_CONFIRM_ABOVE_CAP: "transfer.confirm_above_cap",
  TRANSFER_DUAL_APPROVE: "transfer.dual_approve",
  TRANSFER_CANCEL_PENDING: "transfer.cancel_pending",

  // Conciliação, relatórios, auditoria
  RECONCILIATION_VIEW: "reconciliation.view",
  RECONCILIATION_MATCH: "reconciliation.match",
  REPORT_VIEW: "report.view",
  REPORT_EXPORT: "report.export",
  AUDIT_VIEW: "audit.view",
  AUDIT_EXPORT: "audit.export",

  // Locação — imóveis, contratos, cobranças/repasses recorrentes,
  // despesas/checklists/seguros/manutenções/acordos, vistorias, agente Newton.
  PROPERTY_VIEW: "property.view",
  PROPERTY_CREATE: "property.create",
  PROPERTY_EDIT: "property.edit",
  PROPERTY_DELETE: "property.delete",
  PROPERTY_OWNERSHIP_MANAGE: "property.ownership.manage",
  LEASE_VIEW: "lease.view",
  LEASE_CREATE: "lease.create",
  LEASE_EDIT: "lease.edit",
  LEASE_TERMINATE: "lease.terminate",
  LEASE_RENEW: "lease.renew",
  GUARANTEE_VIEW: "guarantee.view",
  GUARANTEE_MANAGE: "guarantee.manage",
  RENT_VIEW: "rent.view",
  RENT_GENERATE: "rent.generate",
  RENT_REMIND: "rent.remind",
  RENT_MARK_REPASSED: "rent.mark_repassed",
  EXPENSE_VIEW: "expense.view",
  EXPENSE_CREATE: "expense.create",
  EXPENSE_EDIT: "expense.edit",
  EXPENSE_DELETE: "expense.delete",
  CHECKLIST_VIEW: "checklist.view",
  CHECKLIST_MANAGE: "checklist.manage",
  CHECKLIST_TEMPLATE_MANAGE: "checklist.template.manage",
  DEBT_AGREEMENT_VIEW: "debt_agreement.view",
  DEBT_AGREEMENT_CREATE: "debt_agreement.create",
  INSURANCE_VIEW: "insurance.view",
  INSURANCE_MANAGE: "insurance.manage",
  INSPECTION_VIEW: "inspection.view",
  INSPECTION_CREATE: "inspection.create",
  INSPECTION_EXECUTE: "inspection.execute",
  MAINTENANCE_VIEW: "maintenance.view",
  MAINTENANCE_MANAGE: "maintenance.manage",
  CREDIT_ANALYSIS_VIEW: "credit_analysis.view",
  CREDIT_ANALYSIS_DECIDE: "credit_analysis.decide",
  CLIENT_VIEW: "client.view",
  CLIENT_CREATE: "client.create",
  CLIENT_UPDATE: "client.update",
  OWNER_PORTAL_ACCESS: "owner_portal.access",
  TENANT_PORTAL_ACCESS: "tenant_portal.access",
  NEWTON_REQUEST_CREATE: "newton.request.create",
  NEWTON_REQUEST_VIEW: "newton.request.view",
  NEWTON_INTENT_APPROVE: "newton.intent.approve",
  // Propostas (vendas + locação). Primeira RBAC de pipeline do repo: o corretor
  // (preset `sales`) enxerga só as próprias; gestor/owner enxerga todas. O par
  // VIEW_ALL / VIEW_OWN_ONLY espelha CHARGE_VIEW_ALL / CHARGE_VIEW_OWN_DEALS_ONLY.
  PROPOSAL_VIEW_ALL: "proposal.view.all",
  PROPOSAL_VIEW_OWN_ONLY: "proposal.view.own_only",
  PROPOSAL_CREATE: "proposal.create",
  PROPOSAL_SEND: "proposal.send",
  PROPOSAL_CONVERT: "proposal.convert",
} as const;

export type PermissionKey =
  (typeof PERMISSION)[keyof typeof PERMISSION];

export type PermissionMap = Partial<Record<PermissionKey, boolean>>;

export const ALL_PERMISSIONS: PermissionKey[] = Object.values(PERMISSION);

export const PERMISSION_CATEGORIES: Record<string, PermissionKey[]> = {
  "Organização e membros": [
    PERMISSION.ORG_SETTINGS_READ,
    PERMISSION.ORG_SETTINGS_EDIT,
    PERMISSION.ORG_MEMBERS_INVITE,
    PERMISSION.ORG_MEMBERS_CHANGE_ROLE,
    PERMISSION.ORG_MEMBERS_REMOVE,
    PERMISSION.ORG_TRANSFER_OWNERSHIP,
    PERMISSION.ORG_DELETE,
  ],
  "KYC e identidade": [
    PERMISSION.KYC_SUBMIT,
    PERMISSION.KYC_UPLOAD_DOCUMENT,
    PERMISSION.KYC_VIEW_STATUS,
    PERMISSION.API_KEY_ROTATE,
    PERMISSION.API_KEY_VIEW_MASKED,
    PERMISSION.ACCOUNT_CREATE,
    PERMISSION.ACCOUNT_ACTIVATE,
    PERMISSION.ACCOUNT_ARCHIVE,
    PERMISSION.ACCOUNT_PERMISSIONS_MANAGE,
  ],
  "Cobranças": [
    PERMISSION.CHARGE_CREATE_FROM_DEAL,
    PERMISSION.CHARGE_CREATE_AVULSA,
    PERMISSION.CHARGE_VIEW_ALL,
    PERMISSION.CHARGE_VIEW_OWN_DEALS_ONLY,
    PERMISSION.CHARGE_EDIT_DUE_DATE,
    PERMISSION.CHARGE_EDIT_DESCRIPTION,
    PERMISSION.CHARGE_CANCEL,
    PERMISSION.CHARGE_REFUND,
    PERMISSION.CHARGE_RESEND_NOTIFICATION,
    PERMISSION.CHARGE_MARK_RECEIVED_IN_CASH,
  ],
  "Clientes": [
    PERMISSION.CUSTOMER_CREATE,
    PERMISSION.CUSTOMER_EDIT,
    PERMISSION.CUSTOMER_DELETE,
    PERMISSION.CUSTOMER_VIEW_ALL,
    PERMISSION.CUSTOMER_VIEW_OWN_DEALS,
  ],
  "Split e taxas": [
    PERMISSION.SPLIT_VIEW,
    PERMISSION.SPLIT_CONFIGURE,
    PERMISSION.FEES_VIEW,
    PERMISSION.FEES_CONFIGURE,
    PERMISSION.FEES_BRANDING_CONFIGURE,
  ],
  "Transferências e saldo": [
    PERMISSION.FINANCE_BALANCE_VIEW,
    PERMISSION.FINANCE_STATEMENT_VIEW,
    PERMISSION.FINANCE_STATEMENT_EXPORT,
    PERMISSION.TRANSFER_INIT,
    PERMISSION.TRANSFER_CONFIRM_BELOW_CAP,
    PERMISSION.TRANSFER_CONFIRM_ABOVE_CAP,
    PERMISSION.TRANSFER_DUAL_APPROVE,
    PERMISSION.TRANSFER_CANCEL_PENDING,
  ],
  "Conciliação, relatórios e auditoria": [
    PERMISSION.RECONCILIATION_VIEW,
    PERMISSION.RECONCILIATION_MATCH,
    PERMISSION.REPORT_VIEW,
    PERMISSION.REPORT_EXPORT,
    PERMISSION.AUDIT_VIEW,
    PERMISSION.AUDIT_EXPORT,
  ],
  "Locação — Imóveis & Contratos": [
    PERMISSION.PROPERTY_VIEW,
    PERMISSION.PROPERTY_CREATE,
    PERMISSION.PROPERTY_EDIT,
    PERMISSION.PROPERTY_DELETE,
    PERMISSION.PROPERTY_OWNERSHIP_MANAGE,
    PERMISSION.LEASE_VIEW,
    PERMISSION.LEASE_CREATE,
    PERMISSION.LEASE_EDIT,
    PERMISSION.LEASE_TERMINATE,
    PERMISSION.LEASE_RENEW,
    PERMISSION.GUARANTEE_VIEW,
    PERMISSION.GUARANTEE_MANAGE,
    PERMISSION.CREDIT_ANALYSIS_VIEW,
    PERMISSION.CREDIT_ANALYSIS_DECIDE,
  ],
  "Locação — Cobranças & Despesas": [
    PERMISSION.RENT_VIEW,
    PERMISSION.RENT_GENERATE,
    PERMISSION.RENT_REMIND,
    PERMISSION.RENT_MARK_REPASSED,
    PERMISSION.EXPENSE_VIEW,
    PERMISSION.EXPENSE_CREATE,
    PERMISSION.EXPENSE_EDIT,
    PERMISSION.EXPENSE_DELETE,
    PERMISSION.DEBT_AGREEMENT_VIEW,
    PERMISSION.DEBT_AGREEMENT_CREATE,
  ],
  "Locação — Operação": [
    PERMISSION.CHECKLIST_VIEW,
    PERMISSION.CHECKLIST_MANAGE,
    PERMISSION.CHECKLIST_TEMPLATE_MANAGE,
    PERMISSION.INSURANCE_VIEW,
    PERMISSION.INSURANCE_MANAGE,
    PERMISSION.INSPECTION_VIEW,
    PERMISSION.INSPECTION_CREATE,
    PERMISSION.INSPECTION_EXECUTE,
    PERMISSION.MAINTENANCE_VIEW,
    PERMISSION.MAINTENANCE_MANAGE,
  ],
  "Locação — Portais & Newton": [
    PERMISSION.OWNER_PORTAL_ACCESS,
    PERMISSION.TENANT_PORTAL_ACCESS,
    PERMISSION.NEWTON_REQUEST_CREATE,
    PERMISSION.NEWTON_REQUEST_VIEW,
    PERMISSION.NEWTON_INTENT_APPROVE,
  ],
  Propostas: [
    PERMISSION.PROPOSAL_VIEW_ALL,
    PERMISSION.PROPOSAL_VIEW_OWN_ONLY,
    PERMISSION.PROPOSAL_CREATE,
    PERMISSION.PROPOSAL_SEND,
    PERMISSION.PROPOSAL_CONVERT,
  ],
};

export const PERMISSION_LABELS_PT: Record<PermissionKey, string> = {
  [PERMISSION.ORG_SETTINGS_READ]: "Ver configurações da organização",
  [PERMISSION.ORG_SETTINGS_EDIT]: "Editar configurações da organização",
  [PERMISSION.ORG_MEMBERS_INVITE]: "Convidar membros",
  [PERMISSION.ORG_MEMBERS_CHANGE_ROLE]: "Alterar função de membros",
  [PERMISSION.ORG_MEMBERS_REMOVE]: "Remover membros",
  [PERMISSION.ORG_DELETE]: "Deletar organização",
  [PERMISSION.ORG_TRANSFER_OWNERSHIP]: "Transferir propriedade",
  [PERMISSION.KYC_SUBMIT]: "Submeter dados KYC",
  [PERMISSION.KYC_UPLOAD_DOCUMENT]: "Enviar documentos KYC",
  [PERMISSION.KYC_VIEW_STATUS]: "Ver status do KYC",
  [PERMISSION.API_KEY_ROTATE]: "Rotacionar API key da conta Asaas",
  [PERMISSION.API_KEY_VIEW_MASKED]: "Ver API key (mascarada)",
  [PERMISSION.ACCOUNT_CREATE]: "Criar nova conta bancária Asaas",
  [PERMISSION.ACCOUNT_ACTIVATE]: "Selecionar conta bancária ativa da org",
  [PERMISSION.ACCOUNT_ARCHIVE]: "Arquivar conta bancária",
  [PERMISSION.ACCOUNT_PERMISSIONS_MANAGE]: "Gerenciar permissões por conta",
  [PERMISSION.CHARGE_CREATE_FROM_DEAL]: "Criar cobrança a partir de Deal",
  [PERMISSION.CHARGE_CREATE_AVULSA]: "Criar cobrança avulsa",
  [PERMISSION.CHARGE_VIEW_ALL]: "Ver todas as cobranças",
  [PERMISSION.CHARGE_VIEW_OWN_DEALS_ONLY]: "Ver apenas cobranças dos próprios deals",
  [PERMISSION.CHARGE_EDIT_DUE_DATE]: "Alterar vencimento",
  [PERMISSION.CHARGE_EDIT_DESCRIPTION]: "Editar descrição",
  [PERMISSION.CHARGE_CANCEL]: "Cancelar cobrança",
  [PERMISSION.CHARGE_REFUND]: "Estornar cobrança",
  [PERMISSION.CHARGE_RESEND_NOTIFICATION]: "Reenviar notificação ao pagador",
  [PERMISSION.CHARGE_MARK_RECEIVED_IN_CASH]: "Marcar como recebido em dinheiro",
  [PERMISSION.CUSTOMER_CREATE]: "Criar cliente",
  [PERMISSION.CUSTOMER_EDIT]: "Editar cliente",
  [PERMISSION.CUSTOMER_DELETE]: "Deletar cliente",
  [PERMISSION.CUSTOMER_VIEW_ALL]: "Ver todos os clientes",
  [PERMISSION.CUSTOMER_VIEW_OWN_DEALS]: "Ver clientes dos próprios deals",
  [PERMISSION.SPLIT_VIEW]: "Ver configuração de split",
  [PERMISSION.SPLIT_CONFIGURE]: "Configurar split",
  [PERMISSION.FEES_VIEW]: "Ver taxas e descontos",
  [PERMISSION.FEES_CONFIGURE]: "Configurar taxas e descontos",
  [PERMISSION.FEES_BRANDING_CONFIGURE]: "Configurar branding da cobrança",
  [PERMISSION.FINANCE_BALANCE_VIEW]: "Ver saldo",
  [PERMISSION.FINANCE_STATEMENT_VIEW]: "Ver extrato",
  [PERMISSION.FINANCE_STATEMENT_EXPORT]: "Exportar extrato",
  [PERMISSION.TRANSFER_INIT]: "Iniciar transferência",
  [PERMISSION.TRANSFER_CONFIRM_BELOW_CAP]: "Confirmar transferência abaixo do cap",
  [PERMISSION.TRANSFER_CONFIRM_ABOVE_CAP]: "Confirmar transferência acima do cap",
  [PERMISSION.TRANSFER_DUAL_APPROVE]: "Aprovar dual approval",
  [PERMISSION.TRANSFER_CANCEL_PENDING]: "Cancelar transferência pendente",
  [PERMISSION.RECONCILIATION_VIEW]: "Ver conciliação",
  [PERMISSION.RECONCILIATION_MATCH]: "Fazer match de conciliação",
  [PERMISSION.REPORT_VIEW]: "Ver relatórios",
  [PERMISSION.REPORT_EXPORT]: "Exportar relatórios",
  [PERMISSION.AUDIT_VIEW]: "Ver log de auditoria",
  [PERMISSION.AUDIT_EXPORT]: "Exportar log de auditoria",
  // Locação
  [PERMISSION.PROPERTY_VIEW]: "Ver imóveis",
  [PERMISSION.PROPERTY_CREATE]: "Cadastrar imóvel",
  [PERMISSION.PROPERTY_EDIT]: "Editar imóvel",
  [PERMISSION.PROPERTY_DELETE]: "Excluir imóvel",
  [PERMISSION.PROPERTY_OWNERSHIP_MANAGE]: "Gerenciar proprietários do imóvel (%)",
  [PERMISSION.GUARANTEE_VIEW]: "Ver garantia locatícia",
  [PERMISSION.GUARANTEE_MANAGE]: "Gerenciar garantia locatícia",
  [PERMISSION.LEASE_VIEW]: "Ver contratos de locação",
  [PERMISSION.LEASE_CREATE]: "Criar contrato de locação",
  [PERMISSION.LEASE_EDIT]: "Editar contrato de locação",
  [PERMISSION.LEASE_TERMINATE]: "Rescindir contrato de locação",
  [PERMISSION.LEASE_RENEW]: "Renovar contrato de locação",
  [PERMISSION.RENT_VIEW]: "Ver cobranças de aluguel",
  [PERMISSION.RENT_GENERATE]: "Gerar cobrança de aluguel manualmente",
  [PERMISSION.RENT_REMIND]: "Disparar lembrete/régua de cobrança",
  [PERMISSION.RENT_MARK_REPASSED]: "Marcar cobrança como repassada",
  [PERMISSION.EXPENSE_VIEW]: "Ver despesas",
  [PERMISSION.EXPENSE_CREATE]: "Lançar despesa",
  [PERMISSION.EXPENSE_EDIT]: "Editar despesa",
  [PERMISSION.EXPENSE_DELETE]: "Excluir despesa",
  [PERMISSION.CHECKLIST_VIEW]: "Ver checklists",
  [PERMISSION.CHECKLIST_MANAGE]: "Gerenciar checklists do contrato",
  [PERMISSION.CHECKLIST_TEMPLATE_MANAGE]: "Gerenciar modelos de checklist",
  [PERMISSION.DEBT_AGREEMENT_VIEW]: "Ver acordos de dívida",
  [PERMISSION.DEBT_AGREEMENT_CREATE]: "Criar acordo de dívida (parcelamento)",
  [PERMISSION.INSURANCE_VIEW]: "Ver apólices de seguro",
  [PERMISSION.INSURANCE_MANAGE]: "Gerenciar apólices",
  [PERMISSION.INSPECTION_VIEW]: "Ver vistorias",
  [PERMISSION.INSPECTION_CREATE]: "Agendar vistoria",
  [PERMISSION.INSPECTION_EXECUTE]: "Executar vistoria (vistoriador)",
  [PERMISSION.MAINTENANCE_VIEW]: "Ver manutenções",
  [PERMISSION.MAINTENANCE_MANAGE]: "Gerenciar manutenções",
  [PERMISSION.CREDIT_ANALYSIS_VIEW]: "Ver análises de crédito",
  [PERMISSION.CREDIT_ANALYSIS_DECIDE]: "Decidir análise de crédito (aprovar/recusar)",
  [PERMISSION.CLIENT_VIEW]: "Ver clientes de locação",
  [PERMISSION.CLIENT_CREATE]: "Cadastrar cliente de locação",
  [PERMISSION.CLIENT_UPDATE]: "Editar cliente de locação",
  [PERMISSION.OWNER_PORTAL_ACCESS]: "Acessar portal do proprietário",
  [PERMISSION.TENANT_PORTAL_ACCESS]: "Acessar portal do inquilino",
  [PERMISSION.NEWTON_REQUEST_CREATE]: "Criar pedido para Newton",
  [PERMISSION.NEWTON_REQUEST_VIEW]: "Ver pedidos do Newton",
  [PERMISSION.NEWTON_INTENT_APPROVE]: "Aprovar ActionIntent do Newton (HITL)",
  [PERMISSION.PROPOSAL_VIEW_ALL]: "Ver todas as propostas",
  [PERMISSION.PROPOSAL_VIEW_OWN_ONLY]: "Ver apenas as próprias propostas",
  [PERMISSION.PROPOSAL_CREATE]: "Criar proposta",
  [PERMISSION.PROPOSAL_SEND]: "Enviar proposta para assinatura",
  [PERMISSION.PROPOSAL_CONVERT]: "Converter proposta em negócio",
};
